export { SupportCategories } from "./support-categories";
export { SupportContactInfo } from "./support-contact-info";
export { ContactForm } from "./contact-form";
export { ContactInfoCards } from "./contact-info-cards";
export { FAQAccordion } from "./faq-accordion";
export { ShippingOptions } from "./shipping-options";
export { ShippingPolicy } from "./shipping-policy";
export { ReturnSteps } from "./return-steps";
export { ReturnPolicy } from "./return-policy";
export { WarrantyPlans, WarrantyClaim } from "./warranty-plans";
